// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBisFIDAXBPI5eiV24QQiFfaLk4HOOJ3gU',
    appId: '1:804227452203:web:a36c69e38f35ef67dac96e',
    messagingSenderId: '804227452203',
    projectId: 'busrouteapp-17b21',
    authDomain: 'busrouteapp-17b21.firebaseapp.com',
    storageBucket: 'busrouteapp-17b21.firebasestorage.app',
    measurementId: 'G-1XJJQJWDCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtJHQWHlBRx5JoIHvCcNU10hCylOwaQ_Q',
    appId: '1:804227452203:android:c753d5897b388694dac96e',
    messagingSenderId: '804227452203',
    projectId: 'busrouteapp-17b21',
    storageBucket: 'busrouteapp-17b21.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyolkhuY6OQckEF-izt2kqetiKJkWVLts',
    appId: '1:804227452203:ios:e0cdb317ffe65e04dac96e',
    messagingSenderId: '804227452203',
    projectId: 'busrouteapp-17b21',
    storageBucket: 'busrouteapp-17b21.firebasestorage.app',
    iosBundleId: 'com.example.flutterBusRouteReminder',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyolkhuY6OQckEF-izt2kqetiKJkWVLts',
    appId: '1:804227452203:ios:e0cdb317ffe65e04dac96e',
    messagingSenderId: '804227452203',
    projectId: 'busrouteapp-17b21',
    storageBucket: 'busrouteapp-17b21.firebasestorage.app',
    iosBundleId: 'com.example.flutterBusRouteReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBisFIDAXBPI5eiV24QQiFfaLk4HOOJ3gU',
    appId: '1:804227452203:web:24a8229d5ed89393dac96e',
    messagingSenderId: '804227452203',
    projectId: 'busrouteapp-17b21',
    authDomain: 'busrouteapp-17b21.firebaseapp.com',
    storageBucket: 'busrouteapp-17b21.firebasestorage.app',
    measurementId: 'G-FVVVCMQPG8',
  );
}
